language: objective-c

before_install:
  - sudo gem install cocoapods
  - brew update
  - brew install xctool
  
before_script:
  - pod install

script:
  - xctool -workspace SoundCloudStream.xcworkspace -scheme SoundCloudStream -sdk iphonesimulator -arch i386 RUN_CLANG_STATIC_ANALYZER=YES build test

notifications:
  recipients:
    - corrmage+travis-ci@gmail.com
  email:
    on_success: change
    on_failure: always
